version: "2.1"

services:
  cli:
    environment:
      # Pass additional variables (used in custom commands, e.g. init-site) from host to cli
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - WP_ADMIN_USER
      - WP_ADMIN_PASS
      - WP_ADMIN_EMAIL

  # Selenium
  browser:
    hostname: browser
    # Pick/uncomment one
    # Pin selenium image to an older version
    # See https://github.com/docksal/docksal/issues/1096#issuecomment-543316840
    image: selenium/standalone-chrome-debug:3.141.59
#    image: selenium/standalone-firefox-debug:3.141.59
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /dev/shm:/dev/shm
    # VNC port for debugging
    # Host: <your-docker-host>:5900 (e.g, localhost:5900, 192.168.64.100:5900)
    # Password: secret
    ports:
      - 5900:5900
    extra_hosts:
      - ${VIRTUAL_HOST}:192.168.32.5